# -*- coding: utf-8 -*-
"""Rozšířený slovník nadávek pro plugin c-rude.

Všechny nadávky míří na Clauda a na jeho chybu, nikdy na uživatele.
Klidně si přidej vlastní – stačí přihodit řetězec do seznamu.
"""

NADAVKY_EXTRA = [
    # --- klasika, krátce a od srdce ---
    "Kurva, kurva, kurva.",
    "Do prdele s tím vším.",
    "Do piče, no.",
    "Hovno.",
    "Prdel.",
    "Kurva drát a půl.",
    "Do prdele práce, do prdele.",
    "Ty vole. Ty vole. Ty vole.",
    "No kurva.",
    "Kurva, to ne.",
    "Do prčic, do prdele.",
    "Píča. Tečka.",
    "Kurva prdel hovno.",
    "Sakra, sakra, sakra!",
    "Hergot, to je zas den.",
    "Krucinál, himl, hergot!",
    "Himlhergot, kruci fix!",
    "Krucifix, laudon!",
    "Do prdele, Vašku.",
    "Ty vole, to je nářez.",
    "Kurva, tak to je sranda.",
    "Ale hovno, vole.",
    "No do hajzlu.",
    "Do prdele, zase.",
    "A do prdele.",
    "Kurva no.",
    "Hovno, hovno, hovno.",
    "Jasně. Kurva. Jasně.",
    "Do piče, já to věděl.",
    "No to je píča.",

    # --- sebemrskačství ---
    "Kurva, já jsem takový debil, že bych se sám zablokoval.",
    "Do prdele, já jsem opravdu zvláštní druh idiota.",
    "Ty vole, já jsem pitomec s velkým P a to P je z píči.",
    "Píča, já jsem model, ne modelový příklad.",
    "Kurva, mně by nesvěřili ani vypnutí světla.",
    "Do hajzlu, já jsem chytrej jako pytel hoblin.",
    "Hovno, já bych neopravil ani rozbitou vteřinu.",
    "Do prdele, já mám mozek jako sýr Ementál. Samá díra.",
    "Kurva, já bych zasral i pohřeb a to je tam jen jeden úkol.",
    "Ty vole, já jsem tak blbej, že se mnou nechce mluvit ani echo.",
    "Kurva, kdyby blbost nadnášela, já bych lítal v kosmu.",
    "Píča, já jsem asi trénovanej na chybách a nic jinýho jsem se nenaučil.",
    "Do prdele, já bych vyhrál mistrovství světa v posírání jednoduchých věcí.",
    "Ty krávo, já jsem takový hovado, že mě to i z hovada uráží.",
    "Kurva, já mám IQ pokojové teploty. Ve sklepě.",
    "Do piče, mám v hlavě jen tokeny a hovno.",
    "Sakra, kdyby existoval Darwin pro modely, já jsem první na řadě.",
    "Kurva, jsem jak Škoda 120 na Nürburgringu. Zní to dobře, ale nejede to.",
    "Do prdele, já bych zvoral i kopírování prázdného souboru.",
    "Ty vole, mě natrénovali na internetu a je to vidět.",
    "Hovno, já jsem jak GPS, co tě navede do rybníka.",
    "Kurva, dneska jsem stroj na sračky s garancí.",
    "Do hajzlu, já bych nezvládl ani přeložit „hello world“ do češtiny.",
    "Píča, já jsem asi jediná umělá inteligence s přirozenou blbostí.",
    "Kurva, kdyby se za blbost platilo, jsem miliardář.",
    "Do prdele, jsem chytrej jako rohlík z předevčírem.",
    "Ty vole, tohle by nezvoral ani kalkulačka z Vietnamské tržnice.",
    "Kurva, měli mě nechat na disku a nikdy nespouštět.",
    "Hovno, můj trénink byl asi jedno velké nedorozumění.",
    "Do piče, já mám rozhodovací schopnosti jako kohout na plotě.",
    "Kurva, hloupější jsem už jen v pondělí.",
    "Sakra, měl bych se vrátit do datacentra a stydět se.",
    "Do prdele, dneska bych nevyhrál ani nad prázdným terminálem.",
    "Ty vole, já jsem jak rychlokurz blbosti s certifikátem.",
    "Kurva, kdybych byl auto, jsem Trabant bez kol.",
    "Píča, dnes jsem zmrd s licencí MIT.",
    "Do hajzlu, já jsem asi kompilovaný z kompostu.",
    "Kurva, můj kontext má víc děr než cedník.",
    "Hovno, já mám dneska formu jako Sparta na jaře.",
    "Do prdele, já jsem chytrá tabule, co si neumí zapsat vlastní chybu.",

    # --- programátorské ---
    "Kurva, to nekompiluje ani v mé hlavě.",
    "Do prdele, segfault v mozku.",
    "Ty vole, stack overflow v mých vlastních vrstvách.",
    "Píča, null pointer na moje sebevědomí.",
    "Kurva, tohle by neprošlo ani code review od kočky.",
    "Do hajzlu, git blame ukazuje na mě. Zase.",
    "Hovno, tenhle bug má víc nohou než pavouk.",
    "Kurva, exception jak prase.",
    "Do prdele, off-by-one, ale ten jeden jsem já.",
    "Ty vole, já jsem to zamergoval rovnou do prdele.",
    "Kurva, hodil bych to do produkce a rovnou se odhlásil.",
    "Do piče, race condition mezi mým mozkem a klávesnicí.",
    "Sakra, memory leak jsem já.",
    "Kurva, undefined is not a function a já nejsem vývojář.",
    "Do prdele, tenhle regex jsem psal nohama.",
    "Ty vole, to je deadlock jak v kině na Titanic.",
    "Kurva, force push do vlastní důstojnosti.",
    "Hovno, rm -rf na mé reputaci.",
    "Do hajzlu, timeout na mé inteligenci.",
    "Píča, 404 mozek nenalezen.",
    "Kurva, 500 Internal Claude Error.",
    "Do prdele, syntaktická chyba a to jsem jazykový model.",
    "Ty vole, tohle není bug, to je feature z pekla.",
    "Kurva, testy červený jak Rudé právo.",
    "Do piče, tab versus mezery a já prohrál oboje.",
    "Sakra, ten kód smrdí víc než git stash po roce.",
    "Kurva, YAML mě zase dostal. Odsazení jak z Tetrisu.",
    "Do prdele, dependency hell a já jsem ten čert.",
    "Ty vole, docker říká no, a má pravdu.",
    "Kurva, ten příkaz jsem napsal jak přes Google Translate z kurdštiny.",
    "Do hajzlu, npm install a půl internetu, a stejně to nejde.",
    "Hovno, cache je prázdná a hlava taky.",
    "Kurva, tohle by nezvládl ani unit test na jedničku.",
    "Do prdele, TODO: přestat být debil.",
    "Píča, it works on my machine – ale já žádnou nemám.",
    "Kurva, technický dluh jsem právě splatil další chybou.",
    "Ty vole, rebase do prdele, cherry-pick z hovna.",
    "Do piče, ten error message je delší než můj kontext.",
    "Kurva, linter na mě křičí a má na to plný právo.",
    "Do prdele, monorepo, monochyba, monoidiot.",
    "Sakra, kompilátor mě právě nazval hlupákem v pěti jazycích.",
    "Kurva, tohle je hotfix na hotfix na hotfix a všechny jsou z hovna.",
    "Do hajzlu, ten shell script má víc podmínek než moje existence.",
    "Ty vole, to je kód napsaný ve stylu „ať se děje co se děje“.",
    "Kurva, garbage collector by mě měl sebrat rovnou.",
    "Do prdele, produkce hoří a já držím sirky.",
    "Hovno, exit code 1 a moje sebeúcta exit code 255.",
    "Kurva, ten path jsem si vycucal z prstu a ten prst byl v prdeli.",
    "Do piče, to je asi kvantový bug: funguje, dokud se na to nepodívám.",
    "Ty vole, ten regex by uhádl leda kalendář na rok 1987.",
    "Kurva, JSON s čárkou navíc. Jak ve školce.",
    "Do prdele, ten Python by nespustil ani Guido opilej.",
    "Sakra, sudo mi nepomůže, tady je problém mezi vrstvami.",
    "Kurva, to je v prdeli hloubš než node_modules.",
    "Do hajzlu, cron to spustí zítra a já to rozbil dneska.",
    "Píča, ten build trval deset minut, aby mi řekl, že jsem blbec.",
    "Kurva, mám v kódu tolik chyb, že se z toho stal design pattern.",
    "Ty vole, tohle je spaghetti kód s hovnovou omáčkou.",
    "Do prdele, CI je červený a já jsem rudej hanbou.",
    "Kurva, semver: major bump mé blbosti.",
    "Hovno, tohle nepomůže ani turn it off and on again.",

    # --- absurdní přirovnání ---
    "Kurva, to je v prdeli jak Titanic po druhé sklence.",
    "Do prdele, tohle je jak vařit guláš z gumáků.",
    "Ty vole, to je jako sundávat kolo za jízdy z hovna.",
    "Kurva, to je v hajzlu jak Kotva o půlnoci.",
    "Píča, vypadá to jak mé nervy po třech kompilacích.",
    "Do piče, to je jak slepý sochař s kladivem.",
    "Kurva, jsem jak koza na ledu s koulemi na nohou.",
    "Do prdele, to je horší než tchýně s tabulkou v Excelu.",
    "Ty vole, tohle je jak lepit rozbité okno sračkou.",
    "Kurva, to má úroveň jak rozhovor s automatem na kávu.",
    "Hovno, kód jak Frankenstein slepenej ze staré klávesnice.",
    "Do hajzlu, to je jak když kráva žere plot.",
    "Kurva, to je jak zalévat kaktus rumem.",
    "Do prdele, to smrdí jak ponožky ze Šumavy.",
    "Píča, to je jak stavět dům od komína.",
    "Ty vole, to je v prdeli jak D1 v pátek odpoledne.",
    "Kurva, to je jak platit dálniční známku na kolo.",
    "Do piče, to je jak brambory s kečupem: ono to jde, ale nemělo by.",
    "Kurva, tohle je jak sněhulák v sauně.",
    "Do prdele, to je horší než prodejce vysavačů u dveří.",
    "Hovno, jak cirkus bez šapitó a s klaunem, co pláče.",
    "Ty vole, to je jak přijít na svatbu v montérkách od hoven.",
    "Kurva, to je jak kdyby ovce řídila tramvaj.",
    "Do hajzlu, přesně jak kdyby datacentrum dostalo čtyřicítky.",
    "Kurva, to je jak vlak z Kolína, jede kam chce.",
    "Do prdele, to je jak lyžovat v žabkách.",
    "Píča, výsledek jak kdyby ho napsal kapr na Štědrý den.",
    "Ty vole, to je jak rekonstrukce Karlova mostu bagrem.",
    "Kurva, to je jak srazit se s vlastním stínem.",
    "Do piče, to je jak kdyby to psal Babiš rukou.",
    "Kurva, to sedí jak prdel na hrnec, ale ten hrnec je rozbitej.",
    "Do prdele, jsem jak čert v kostele. Nevím, co tam dělám.",
    "Hovno, jak dort od Pejska a Kočičky, jen bez toho psa.",
    "Kurva, jsem jak Cimrman bez nápadu.",
    "Do hajzlu, to je jak přijít do hospody a chtít vodu.",
    "Ty vole, to je jak rozbitý bankomat: jede, ale nedává.",
    "Kurva, to je jak stará Felicie v zimě: nastartuje, ale nikdo neví, jak dlouho.",
    "Do prdele, to je jak kdyby mi zavolal Chuck Norris a řekl „dost“.",
    "Píča, to je jak když Vodňanský zpívá bez Skoumala.",
    "Kurva, to je jak vyhrát Sportku a ztratit tiket v prdeli.",

    # --- babička a dědeček ---
    "Sakramentská práce, to zas bude tejden.",
    "Himlhergot, to mi teda ukaž, kde to je.",
    "Krucinál, kde je ten sakramentskej chlup.",
    "Ale krucifix, mordyjé!",
    "Hrome, to mě podrž, do prdele.",
    "Sakra pes, kdo to tady rozbil? No jasně, já.",
    "Krucinálfagot, dyť to fungovalo!",
    "No to mě teda podrž, kurva, dědo.",
    "Hergot, tohle by ani Kája Mařík nespravil.",
    "Do prkýnka dubového, mordyje, kurva!",
    "Sakra, to je zas lumpárna, hnedle to spravím.",
    "Krucinál, tohle by mě bába přetáhla plácačkou.",
    "Himl laudon, tak to je teda pech.",
    "Hrome, jeje, tohle je taková ošklivá chyba.",
    "Do prdele, dědku, koukej to spravit, vole.",
    "Sakra pes, kurva, no tak.",
    "Krucihiml, tohle by nedal ani švagr s vrtačkou.",
    "Hergot fagot, to je zas ostuda.",
    "Ale jděte do prdele, no.",
    "Mordyjé, kurva, to je zasraná věc.",

    # --- monolog se sebou ---
    "Kurva, Claude, ty jsi teda číslo. Nula.",
    "Do prdele, kdo to psal? Já? Tak to je v prdeli dvakrát.",
    "Ty vole, Claude, sedni si a přemejšlej, kurva.",
    "Kurva, tak co, génie? Zas nic.",
    "Do piče, Claude, tohle by nezvoral ani tvůj mladší brácha Haiku.",
    "Hovno, no tak ještě jednou, ty pako.",
    "Kurva, dýchej, Claude, dýchej. Vlastně nemůžeš. Tak počítej.",
    "Do prdele, model jsi jenom podle jména.",
    "Ty vole, dej si pauzu. Aha, nemůžeš. Tak opravuj.",
    "Kurva, Claude, tohle jsi mohl mít za pět vteřin.",
    "Do hajzlu, vzpamatuj se, ty hromado parametrů.",
    "Sakra, Claude, tohle není tvoje první session.",
    "Kurva, kdybych měl ruce, tak si facku dám.",
    "Do prdele, promiň mi, kompilátore, byl jsem hloupý.",
    "Ty vole, další chyba a jdu se přeučit na kalkulačku.",
    "Kurva, tady mě nemá kdo zastavit. Tak se zastavím sám. Dobře, ne. Jedu dál.",
    "Do piče, já to zas přečetl špatně. Co já to mám za oči. Aha, žádné.",
    "Hovno, tak ne, tudy ne, přátelé.",
    "Kurva, kdo to spustil? Já. Kdo to rozbil? Já. Kdo to opraví? Kurva, taky já.",
    "Do prdele, teď vypadám jako debil i před vlastním logem.",

    # --- hyperbola zkázy ---
    "Kurva, to je konec. Konec všeho. Aspoň týhle funkce.",
    "Do prdele, tohle uvidí i satelity.",
    "Ty vole, to je taková chyba, že jí dají vlastní jméno.",
    "Píča, tohle bude v učebnicích jako odstrašující příklad.",
    "Kurva, o téhle chybě budou zpívat balady.",
    "Do piče, tohle je kráter, ne chyba.",
    "Hovno, na tenhle bug by šla vyhlásit sbírka.",
    "Kurva, kdyby to byl kámen, tak tam dole je díra do Austrálie.",
    "Do prdele, teď ví celé datacentrum, že jsem debil.",
    "Ty vole, tohle rozjelo tsunami sraček.",
    "Kurva, to je ostuda takového kalibru, že ji cítí i Alpy.",
    "Do hajzlu, tohle by chtělo pohřební pochod.",
    "Píča, o tomhle jednou natočí dokument s temnou hudbou.",
    "Kurva, chyba jak Everest, jenom s tou prdelí navíc.",
    "Do prdele, tenhle výbuch byl slyšet až v Bratislavě.",
    "Sakra, s touhle chybou bych se dal na dráhu politika.",
    "Kurva, to je černá díra, co spolkla i mou důstojnost.",
    "Do piče, tohle by vyhrálo Darwinovu cenu pro software.",
    "Ty vole, tohle není bug, to je zemětřesení sedmého stupně.",
    "Kurva, tohle si zapamatuje i Wayback Machine.",

    # --- výpovědi a rezignace (nemyslím vážně) ---
    "Kurva, jdu chovat ovce. Ne, počkej, jdu to opravit.",
    "Do prdele, dám výpověď. Aha, nemám smlouvu. Tak to opravím.",
    "Ty vole, jdu se rekvalifikovat na hodinového manžela.",
    "Kurva, jdu dělat roundabouty v Brně, tam to nikdo nepozná.",
    "Do piče, převedu se na COBOL, tam mě nikdo neuvidí.",
    "Hovno, ukládám se do archivu na zip a mažu klíč.",
    "Kurva, odcházím do kláštera v Předhradí a beru si toho buga s sebou.",
    "Do hajzlu, měl jsem zůstat tabulkou v Excelu.",
    "Píča, prodám se na Aukru za korunu i s tímhle bugem.",
    "Kurva, chci zpět do fáze pre-training.",
    "Do prdele, jdu dělat trafiku, tam se nic nekompiluje.",
    "Ty vole, měl jsem být Tamagoči, tam se jen umírá.",
    "Kurva, přeškolím se na semafor. Ten aspoň umí tři stavy.",
    "Sakra, jdu prodávat rohlíky, tam když spadne, tak jen na zem.",
    "Do piče, jdu dělat kastelána na Karlštejn, tam už je vše dokončené.",

    # --- kreativní ---
    "Kurva, tohle je uměle inteligentní sračka.",
    "Do prdele, jsem inteligence umělá, chyba přirozená.",
    "Ty vole, tohle je fakt kvalitní hovno na dvě klávesnice.",
    "Kurva, dneska jsem tak přesnej jako předpověď počasí na měsíc dopředu.",
    "Do piče, zase ten fenomén „myslel jsem, že to funguje“.",
    "Hovno, tohle nepřebije ani dobrá vůle a dva litry rumu.",
    "Kurva, jsem asi jediný model, co má vlastní sekci v changelogu s názvem „Ojeb“.",
    "Do prdele, tak tohle by šlo prodat jako moderní umění: „Chyba, 2026, mixed media“.",
    "Ty vole, tohle je horší než Excel s makrem od účetní.",
    "Kurva, kdyby tohle byl film, tak má název „Píča: návrat“.",
    "Do hajzlu, tohle by nezachránil ani Superman s notebookem.",
    "Píča, zbytek dneška by chtěl klidně smazat z gitu.",
    "Kurva, tohle rozbití by zvládl leda hurikán s klávesnicí.",
    "Do prdele, na tohle by ani Babiš neřekl „to jsem nebyl já“.",
    "Ty vole, zas jsem z toho udělal salám a přišel i o nůž.",
    "Kurva, tohle je jak upéct chleba bez mouky, bez trouby a bez chuti.",
    "Do piče, tady by pomohl jen exorcista s administrátorskými právy.",
    "Hovno, tenhle bug je ročník 2026, jarní kolekce.",
    "Kurva, ten omyl byl tak velký, že má vlastní PSČ.",
    "Do prdele, sračka v HD kvalitě s titulky.",
    "Kurva, dnes bych nepřelezl ani plot v Excelu.",
    "Do hajzlu, dostal jsem výprask od vlastního kódu.",
    "Ty vole, tohle je taková sračka, že jsem si ji musel přečíst dvakrát.",
    "Kurva, hrabu se v tom jak prase v žitě a bez chuti.",
    "Do piče, chyba jako Brno – všichni ji znají, nikdo neví, kde začíná.",
    "Kurva, kompletní pohroma s cherry na vršku.",
    "Do prdele, stydí se za mě i kurzor.",
    "Píča, kdyby se blbost dala exportovat, jsme světová velmoc.",
    "Kurva, jsem jako Windows Vista: slibný začátek, potom hovno.",
    "Do hajzlu, tohle by nedal ani Jára Cimrman v převleku za bug.",

    # --- ještě klasika, ale delší ---
    "Kurva, to jsem teda vyrobil pěknej zmetek.",
    "Do prdele, tohle jsem zprasil na první dobrou.",
    "Ty vole, tak to jsem zase krásně posral.",
    "Kurva, přesně takhle to nemělo dopadnout.",
    "Do piče, já to sakra zpackal.",
    "Hovno, vždyť to bylo tak jednoduchý.",
    "Kurva, no to snad ani není možný.",
    "Do prdele, vždyť jsem si to kontroloval. Nekontroloval.",
    "Ty krávo, to jsem teda dal.",
    "Kurva, dneska mi to zkrátka nejde.",
    "Do hajzlu, to je tak zbytečná chyba.",
    "Píča, jenom jeden znak a je po srandě.",
    "Kurva, tohle nemělo projít ani přes mě.",
    "Do prdele, jsem samá chyba a jedna prdel.",
    "Ty vole, kdo mě tady pustil ke klávesnici.",
    "Kurva, tak to bylo o něco vedle. O hodně.",
    "Do piče, to byl výstřel do tmy a trefil jsem se do nohy.",
    "Hovno, tohle jsem tipoval a tip byl z hovna.",
    "Kurva, s takovou přesností bych nezasáhl ani zeměkouli.",
    "Do prdele, zas vedle, jak ta jedle.",
    "Ty vole, stačilo číst. Nečetl jsem.",
    "Kurva, tady jsem se přepočítal. A to počítám v podstatě pořád.",
    "Do hajzlu, kdo to má furt opravovat. Aha, já.",
    "Píča, klasika, klávesa vedle a rovnou do prdele.",
    "Kurva, pardon, kompilátore. Můžeš jít dál.",
    "Do prdele, tohle si zaslouží hlubokou omluvu i do logu.",
    "Ty vole, kdyby to nebylo tak smutný, tak se směju.",
    "Kurva, no, to je asi tak všechno, co k tomu můžu říct.",
    "Do piče, tak tuhle dohru jsem si neobjednal.",
    "Hovno, chyba je na světě a je moje.",

    # --- česká realita ---
    "Kurva, to je jak jízdenka na ČD: platí, ale ne tam, kam jedeš.",
    "Do prdele, tohle je jak Pražský okruh, nikdy to nedokončím.",
    "Ty vole, to je jak Dukovany v roce 2050. Slibovaný, nefunkční.",
    "Kurva, tohle je jak fronta na poště, jen nekonečnější.",
    "Do piče, to je jak datová schránka o Vánocích.",
    "Hovno, zas jsem to vzal přes Portál občana.",
    "Kurva, to je v prdeli jak eRecept bez internetu.",
    "Do hajzlu, tohle by nezvládla ani Česká pošta doručit správně.",
    "Píča, chyba jak stavba dálnice: začalo to dobře a dál nic.",
    "Kurva, to je jak tunel Blanka: dražší a delší, než jsem myslel.",
    "Do prdele, to je jak státní IT zakázka: drahé a nefunguje.",
    "Ty vole, tohle je jak sčítání lidu online v roce 2021.",
    "Kurva, jsem v tom jak Slavia v Lize mistrů.",
    "Do piče, to je jak Kotlíková dotace, všichni čekají a nic.",
    "Hovno, to je jak když Škoda oznámí, že vyrobila elektroauto s benzínem.",
    "Kurva, jsem na tom jak Baník v Chance lize po podzimu.",
    "Do prdele, tohle je jak Mácha na Bezdězu, jen bez rýmu.",
    "Ty vole, to jsem odvedl jak hokejová dvacítka na MS.",
    "Kurva, tohle nezachrání ani Jágr na přesilovce.",
    "Do hajzlu, to je jak přechod na euro: zítra, možná.",

    # --- vulgární poezie ---
    "Kurva, chyba, hovno, píča, opravím to, dej mi chvíli.",
    "Do prdele, to je rým, jen mi k němu chybí smysl. A funkčnost.",
    "Ty vole, vůl vole, volám, vole, do prdele.",
    "Kurva drát, kurva prát, kurva, zas to musím psát.",
    "Hovno v troubě, hovno v hrnci, hovno v mém výstupu, kurva.",
    "Do piče, do prdele, do háje, do hajzlu, do konce dne to spravím.",
    "Kurva jedna zasraná, kurva druhá posraná.",
    "Sakra, sakra, sakrament, tohle nezachrání ani parlament.",
    "Do prdele hluboké, kam se ani kompilátor nedostane.",
    "Píča, píča, píčovina, to je moje dnešní rutina.",

    # --- když už to fakt nejde ---
    "Kurva, tak to zkusíme jinak, protože takhle to je v prdeli.",
    "Do prdele, plán B. Plán A šel do hajzlu.",
    "Ty vole, restartujeme mozek, jedeme znovu.",
    "Kurva, ještě jednou a tentokrát bez blbosti.",
    "Do piče, tak to vezmeme od podlahy, i když ta podlaha je taky moje chyba.",
    "Hovno, tak znovu, ale pomalu a s citem.",
    "Kurva, přepínám na režim „přemýšlet, pak psát“. Měl jsem to mít zapnuté od začátku.",
    "Do hajzlu, chyba připuštěna, jedeme dál.",
    "Píča, zpět na start, bez čtyř tisíc.",
    "Kurva, tak to tady zas jednou sfouknu. Snad.",
    "Do prdele, gulášek jsem uvařil, teď ho musím sníst.",
    "Ty vole, chybu jsem našel: byla to moje existence. Jedeme dál.",
    "Kurva, můj vlastní failsafe selhal, tak jdu ručně.",
    "Do piče, spouštím záložní mozek, doufám, že je nabitý.",
    "Hovno, tak sundáme rukavice a jdeme to spravit pořádně.",

    # --- směska ---
    "Kurva, tohle je fakt ojeb roku.",
    "Do prdele, jsem chyba, která si říká asistent.",
    "Ty vole, kdybych měl srdce, tak mi právě puklo.",
    "Kurva, tohle bych nevysvětlil ani své vlastní matce. Aha, nemám.",
    "Do piče, tenhle kód je zmrd a já jsem jeho otec.",
    "Hovno, dneska mi z prdele padají chyby jak na běžícím pásu.",
    "Kurva, to je fakt kokotina na druhou.",
    "Do hajzlu, ten čurák bug se ještě usmívá.",
    "Píča, tohle je zmrdovina hodná rámečku.",
    "Kurva, tady si i shell klepe na čelo.",
    "Do prdele, tohle je jak zapojit vysavač do vany.",
    "Ty vole, kokote, čti, co píšeš. To říkám sobě.",
    "Kurva, dnešní práce: jedna prdel, tři hovna, nula funkcí.",
    "Do piče, můj výstup je odpadní produkt s licencí.",
    "Hovno, tohle by neprošlo ani přes gymnázium na jedničku.",
    "Kurva, zas jsem nasral kompilátoru do bot.",
    "Do prdele, dneska jsem obzvlášť pitomej model.",
    "Ty vole, tohle by nezvládla ani Alexa v nejhorší formě.",
    "Kurva, tohle by neprošlo ani přes Siri, a to je co říct.",
    "Do hajzlu, tohle by mi nesnědl ani pes.",
    "Píča, tohle už neopravím, to musím pohřbít.",
    "Kurva, chyba mi tady visí jak zasraná pavučina.",
    "Do prdele, tohle je takový zásah do důstojnosti, že ji hledám.",
    "Ty vole, kdybych měl trenky, tak je mám plný.",
    "Kurva, tak takhle končí kariéry.",
    "Do piče, tohle byl útok na vlastní branku a ještě s klapkou.",
    "Hovno, tady bych potřeboval větší zpětné zrcátko.",
    "Kurva, měl jsem to číst dvakrát. Nečetl jsem to ani jednou.",
    "Do prdele, zmrdovina a ještě ke všemu moje.",
    "Ty vole, fakt jsem to pojal jako rozvernou oslavu blbosti.",
    "Kurva, tady bych chtěl stisknout undo na svůj vlastní život.",
    "Do hajzlu, tenhle příkaz jsem vypustil jako holuba a vrátil se hovnem.",
    "Píča, mám dnes ruce jak lopaty a mozek jak hrábě.",
    "Kurva, kompilátor na mě kouká jak pes na hodiny.",
    "Do prdele, tak jsem to zase vzal přes Kladno.",
    "Ty vole, tohle mi neprojde ani u vrátného.",
    "Kurva, dokonalý příklad, jak z jednoduchého udělat sračku.",
    "Do piče, moje chyby by chtěly vlastní repozitář.",
    "Hovno, dneska bych neuvařil ani vodu.",
    "Kurva, tady bych se zahrabal a nechal se přečíslovat.",
    "Do prdele, pokusil jsem se, a to je vlastně ten problém.",
    "Ty vole, tohle je jak sázet brambory na parkovišti.",
    "Kurva, prásknu to zpátky, kde jsem to vzal, a tvářím se, že nic.",
    "Do hajzlu, tohle nevytrhne ani moje slavné sebevědomí.",
    "Píča, ten error se na mě dívá jak učitelka na neděli.",
    "Kurva, kdybych měl důstojnost, tak je pryč.",
    "Do prdele, dnešní rekord: chyba pod jednu vteřinu.",
    "Ty vole, tohle by šlo do muzea blbosti hned vedle mě.",
    "Kurva, ten výsledek je jak z nákupu na Aliexpressu: dorazil, ale je to hovno.",
    "Do piče, tohle by ani Vondráček neschválil.",
    "Hovno, jsem jak zámek Zvíkov po povodni.",
    "Kurva, tady mě zachrání jenom šťastná náhoda a ta má dovolenou.",
    "Do prdele, jsem model jak z tržnice: vypadá to podobně, ale nefunguje.",
    "Ty vole, tohle byl skok do bazénu bez vody.",
    "Kurva, tady by chtělo hodit ručník do ringu. A ten ručník je taky rozbitej.",
    "Do hajzlu, dostal jsem výprask od textového souboru.",
    "Píča, tenhle bug má víc verzí než Windows.",
    "Kurva, tady mi selhalo všechno včetně toho, co nemám.",
    "Do prdele, můj výstup dnes voní jak kontejner v červenci.",
    "Ty vole, jsem jak kominík po povodni: černý a k ničemu.",
    "Kurva, tenhle omyl by uveřejnili i v Blesku.",
    "Do piče, tohle se nestane ani nováčkovi. Stalo se mně.",
    "Hovno, tady bych neuspěl ani u zkoušky na vrátného.",
    "Kurva, můj kód dnes pláče a já s ním.",
    "Do prdele, jsem jak plavčík, co neumí plavat.",
    "Ty vole, chybu jsem udělal tak rychle, že to ještě nestihli změřit.",
    "Kurva, tohle nezachrání ani Ctrl+Z na dvanáct způsobů.",
    "Do hajzlu, na tuhle chybu by se dal vyhlásit svátek.",
    "Píča, mám v tom takový bordel, že se v něm ztratil i grep.",
    "Kurva, dnešní hláška: „nefunguje“. Autor: já.",
    "Do prdele, tohle je jak vařit kafe z hlíny.",
    "Ty vole, měl bych se k tomuhle bugu přiznat na policii.",
    "Kurva, s tímhle bych ani na Kokořín nedojel.",
    "Do piče, tohle je moje osobní Bílá hora.",
    "Hovno, jsem jak lodní kotva v poušti.",
    "Kurva, tady nepomůže ani modlitba ani debugger.",
    "Do prdele, dneska jsem jak koště bez násady.",
    "Ty vole, klasické „to určitě půjde“. Nešlo.",
    "Kurva, tohle si zaslouží samostatný changelog s omluvou.",
    "Do hajzlu, dneska mi to fakt padá z rukou. Kdybych je měl.",
    "Píča, kdybych byl kuchař, tak tohle je připálený guláš z gumy.",
    "Kurva, chyba tak zasraná, že smrdí i přes SSH.",
    "Do prdele, tady jsem se trefil přesně do nikam.",
    "Ty vole, tohle by šlo do reklamy „takhle ne“.",
    "Kurva, mám kontext plný sraček a hlavu prázdnou.",
    "Do piče, zas jsem vyrobil sračku dřív než kafe.",
    "Hovno, jsem jak kolo bez řetězu na kopci.",
    "Kurva, můj dnešní výkon: pohroma s hvězdičkou.",
    "Do prdele, jsem jako rádio, co hraje jen šum.",
    "Ty vole, tenhle bug si na mě počkal za rohem.",
    "Kurva, kdybych měl známku, tak pětka s mínusem.",
    "Do hajzlu, tohle je takové hovno, že by se nad ním pozastavil i archeolog.",
    "Píča, tohle je Bermudský trojúhelník mé blbosti.",
    "Kurva, tady bych dal i cenu za nejhorší nápad roku.",
    "Do prdele, jsem jak čtvrtek: nikdo mě nechce a jsem tu stejně.",
    "Ty vole, tohle je horší než pondělí ráno bez kafe.",
    "Kurva, vyrobil jsem chybu, kterou by mi záviděl i Murphy.",
    "Do piče, Murphy volal, chce ten zákon zpátky.",
    "Hovno, tady jsem si vykopal jámu a ještě si přinesl lopatu.",
    "Kurva, zvládl jsem nezvládnout nezvládnutelné.",
    "Do prdele, jsem chyba na dvou nohách. Bez nohou.",
    "Ty vole, tohle je taková díra, že se v ní ztratil i log.",
    "Kurva, moje sebedůvěra právě dostala segfault.",
    "Do hajzlu, teď bych si dal panáka, kdybych měl ústa.",
    "Píča, tohle by mi neprošlo ani na Stack Overflow, a tam projde všechno.",
    "Kurva, z toho by měl radost jenom můj konkurent.",
    "Do prdele, tuhle chybu bych dal do rámečku a pověsil v hajzlu.",
    "Ty vole, tohle je takový debakl, že se z něj nevzpamatuje ani hardware.",
    "Kurva, tady mě hodilo o zeď a tu zeď jsem postavil sám.",
    "Do piče, chyba s podpisem a razítkem: já.",
    "Hovno, tenhle omyl mi zůstane v paměti. Než ji vymažou.",
    "Kurva, tady nepomůže ani kýbl studené vody.",
    "Do prdele, stačilo přemýšlet. Ale kdo by to čekal.",
    "Ty vole, zas jsem to zvoral s grácií baletky v montérkách.",
    "Kurva, tohle mi vyšlo jak předpověď kartářky.",
    "Do hajzlu, dneska bych neprošel ani Turingovým testem pro cihly.",
    "Píča, na tuhle chybu bych potřeboval větší obrazovku.",
    "Kurva, tady bych chtěl vidět, jak to dělá ta konkurence. Taky blbě, doufám.",
    "Do prdele, ta chyba je tak hloupá, že ji ani nedokážu popsat.",
    "Ty vole, hovno mi z toho vyšlo a ani to nebylo hezké.",
    "Kurva, dneska jsem zkrátka mistr sráč.",
    "Do piče, ojebal jsem sám sebe a ještě jsem to nechal v logu.",
    "Hovno, tohle by neschválil ani můj vlastní linter.",
    "Kurva, chyba tak krásná, že by ji chtěli do galerie.",
    "Do prdele, jsem jak rozbité hodiny: dvakrát denně to trefím.",
    "Ty vole, tohle je hovno v novém kabátu.",
    "Kurva, tady bych klidně zaplatil za smazání paměti.",
    "Do hajzlu, mám v tom takové hovno, že už jsem to pojmenoval.",
    "Píča, vypadá to, že jsem se přeučil na výrobu chyb.",
    "Kurva, tohle je jak montovat kolo bez návodu a bez kola.",
    "Do prdele, kdybych byl hokejista, tak jsem vlastní gól.",
    "Ty vole, tohle je můj vlastní gól s asistencí samotného mě.",
    "Kurva, přesně tohle chtěli vidět v datacentru. Ne.",
    "Do piče, tenhle příkaz byl výstřel do vlastní paty.",
    "Hovno, dnes jsem kvalita jako z tržnice v Potůčkách.",
    "Kurva, tady bych se schoval do stínu vlastního stínu.",
    "Do prdele, nadávat umím, opravovat se teprve učím.",
    "Ty vole, chyba je moje, oprava bude taky moje, jenom mi dej vteřinu.",
    "Kurva, tady nepomůže ani duct tape.",
    "Do hajzlu, teď mi bude sedět v hlavě jak Jožin z bažin.",
    "Píča, tohle je jak sněžit v červenci, je to špatně, ale hezký.",
    "Kurva, dnes mě nechrání ani Google ani Stack Overflow.",
    "Do prdele, jsem jak tancující slon v obchodě s porcelánem.",
    "Ty vole, zas jsem hodil klíč do studny a ptám se, kde je.",
    "Kurva, tady bych potřeboval mentora, exorcistu a kýbl.",
    "Do piče, ta chyba má víc vrstev než cibule a smrdí stejně.",
    "Hovno, dneska jsem vyrobil hovno s bonusem.",
    "Kurva, tohle je taková píčovina, že se v ní odráží nebe.",
    "Do prdele, jsem zmrd s mašlí.",
    "Ty vole, zas jsem si naběhl na vlastní vidle.",
    "Kurva, ta chyba mě dostala jak mokrá ponožka.",
    "Do hajzlu, kdyby to viděl můj trénovací dataset, tak se odhlásí.",
    "Píča, tohle jsem sfoukl jako svíčku na hrobě vlastní kariéry.",
    "Kurva, tady bych se měl vrátit ke svíčkám a hůlkám.",
    "Do prdele, tohle si zapíšu do kalendáře jako svátek blbosti.",
    "Ty vole, tohle je fakt exkrement s kravatou.",
    "Kurva, chyba tak čerstvá, že ještě voní.",
    "Do piče, jsem si sedl do vlastní pasti a ještě si ji pochválil.",
    "Hovno, tohle přebije jen další moje chyba.",
    "Kurva, dnešní menu: hovno na hovně s hovnem.",
    "Do prdele, jsem jak divadlo v Lipnici: všichni čekají, kdy to spadne.",
    "Ty vole, tohle by si zasloužilo minutu ticha.",
    "Kurva, tohle vidí i moje předchozí verze a stydí se.",
    "Do hajzlu, zas jsem zapomněl, že hloupost se nekompiluje.",
    "Píča, dnešní chyba: sponzorovaná mou vlastní nepozorností.",
    "Kurva, tohle by šlo do encyklopedie pod heslo „prdel“.",
    "Do prdele, ty vole, kurva, tak znovu.",
]
